### ISSUE TITLE
苏州公交查询（JSbox）

### ISSUE THREAD

**Issue by JEGNUI** [CoderHRXu/BusPreview#1]
哥、苏州公交的查询接口变成“ http://app.2500.tv/bus1/lineInfo1.php”了，我按照流程修改接口，但是上方不能显示还有几站到达了，只显示未知。

**Comment by CoderHRXu** [comment]
> 哥、苏州公交的查询接口变成“ [http://app.2500.tv/bus1/lineInfo1.php”了，我按照流程修改接口，但是上方不能显示还有几站到达了，只显示未知。](http://app.2500.tv/bus1/lineInfo1.php%E2%80%9D%E4%BA%86%EF%BC%8C%E6%88%91%E6%8C%89%E7%85%A7%E6%B5%81%E7%A8%8B%E4%BF%AE%E6%94%B9%E6%8E%A5%E5%8F%A3%EF%BC%8C%E4%BD%86%E6%98%AF%E4%B8%8A%E6%96%B9%E4%B8%8D%E8%83%BD%E6%98%BE%E7%A4%BA%E8%BF%98%E6%9C%89%E5%87%A0%E7%AB%99%E5%88%B0%E8%BE%BE%E4%BA%86%EF%BC%8C%E5%8F%AA%E6%98%BE%E7%A4%BA%E6%9C%AA%E7%9F%A5%E3%80%82)

api地址已更新为:   http://app.2500.tv/bus1/api_line_status_a.php
